### ISSUE TITLE
Lower logging level

### ISSUE THREAD

**Issue by TheDailySpank** [nikos-glikis/nsfw-docker#1]
Is there a way to lower the logging level on this docker image?

I've tried setting the logging level in the python script but get an error stating it doesn't know the os.environ variable. Sorry, I'm not terribly familiar with python.

`os.environ['GLOG_minloglevel'] = '2'`
As per http://stackoverflow.com/questions/29788075/setting-glog-minloglevel-1-to-prevent-output-in-shell-from-caffe

The logging causes the docker image on my Mac to enlarge to 50+GB in just a few hours of processing images and I really don't need any of the debugging level information (or anything really at all as I know all my images either work or don't).

**Comment by nikos-glikis** [comment]
Hello, I put the command on the correct position. The debugging now is disabled. Can you please verify ?

Thanks

**Comment by TheDailySpank** [comment]
Yes, I can confirm it's working now. Thank you!
