### ISSUE TITLE
Check failed: axis_index < num_axes()

### ISSUE THREAD

**Issue by ghost** [nikos-glikis/nsfw-docker#2]
Brand new install of Ubuntu 17.10 in a virtual machine (also tested on a laptop), I go through the installation instructions, everything seems fine and when I try to run it I get this:

```
libdc1394 error: Failed to initialize libdc1394
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0308 20:22:54.235227     1 blob.hpp:122] Check failed: axis_index < num_axes() (1 vs. 1) axis 1 out of range for 1-D Blob with shape 2 (2)
*** Check failure stack trace: ***
```

Any ideas?

**Comment by nikos-glikis** [comment]
Hello,

I downloaded ubuntu 17.10 and installed a fresh system.

The library works, I only get one warning - but after that the library responds correctly:

libdc1394 error: Failed to initialize libdc1394

What is the command you are running exactly ? Did you had this error in the ./build_docker.sh command or when you runned the command ? 

One thing I runned differently is the install of docker - You need to install ce edition. I don't know if that has anything to do with the error you are experiencing. I have updated the link in README.

Can you please try again and tell me if it works ?

https://docs.docker.com/install/linux/docker-ce/ubuntu/

Thanks
