### ISSUE TITLE
this file is not run Cpu only mode(witout docker)

### ISSUE THREAD

**Issue by DevaDinesh21** [nikos-glikis/nsfw-docker#5]
classify_nsfw.py file is not run witout docker.....am try to run cpu only method but this code compile error UTF-8 unicode error apears they cant convert string to bytes

**Comment by nikos-glikis** [comment]
Hello,

Yes the classify_nsfw.py does not run without Docker. That is why I created this project. Because dependencies were hard ti install, so you can it through Docker.

Can you exactly what you are trying to do ?

Thanks

**Comment by DevaDinesh21** [comment]
am using nsfw in my website so am try to build your source code without docker (CPU only mode)..but i got unicodedecode error

**Comment by nikos-glikis** [comment]
That is not my file, I just edited it a bit.

This is the original project: https://github.com/yahoo/open_nsfw/
